RO_log/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from .models import RO
from . import api_views


app_name = 'RO_log'

urlpatterns= [
    path('',views.ROTodayArchiveView.as_view(),name='archive_day'),
    path('login/',views.CustomLoginView.as_view(),name='login'),
    path('logout/',views.LogoutView.as_view(),name='logout'),
    path('report/',views.ROList.as_view(),name='report'),
    path('create/',views.ROCreate.as_view(),name='create'),
    path('update/<int:pk>/', views.ROUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', views.RODelete.as_view(), name='delete'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('payperiod/',views.PayPeriodList.as_view(),name='payperiod-list'),
    path('payperiod/create',views.PayPeriodCreate.as_view(),name='payperiod-create'),
    path('payperiod/update/<int:pk>/',views.PayPeriodUpdate.as_view(),name='payperiod-update'),
    path('payperiod/delete/<int:pk>/',views.PayPeriodDelete.as_view(),name='payperiod-delete'),
    path('dashboard/',views.DashboardView.as_view() ,name='dashboard'),
    path('api/payperiod/',api_views.PayPeriodList.as_view()),
    path('api/ro/',api_views.ROList.as_view()),

]

ROtracker/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include ('RO_log.urls')),

]

RO_log/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Sum
from django.utils import timezone
from django.contrib.auth.models import User
import datetime
# Create your models here.


class PayPeriod(models.Model):
    name = models.CharField(max_length=200,unique=True)
    user = models.ForeignKey(User,on_delete = models.CASCADE,null=True)
    start_date = models.DateField()
    end_date = models.DateField()

    def sold_hours(self):
        hours = self.annotate(Sum('ro__hours_sold'))
        return hours

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("RO_log:payperiod-list")

class RODailyManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(completed_date=timezone.now())

class ROMonthlyManager(models.Manager):
    def get_queryset(self):
        field_name = "pay_period"
        obj=super().get_queryset().first()
        field_value = getattr(obj,field_name)
        return super().get_queryset().filter(pay_period=field_value)

class RO(models.Model):
    RO_number = models.IntegerField()
    user = models.ForeignKey(User,on_delete = models.CASCADE,null=True)
    hours_sold = models.DecimalField(max_digits=5,decimal_places=2)
    work_performed = models.CharField(max_length=200)
    completed_date = models.DateField(default=timezone.now())
    pay_period = models.ForeignKey(PayPeriod,on_delete=models.RESTRICT,null=True)

    def __str__(self):
        return self.RO_number

    def get_absolute_url(self):
        return reverse("RO_log:archive_day")


    class Meta:
        ordering = ['-completed_date']

    objects = models.Manager() # The default manager.
    daily_objects = RODailyManager()
    monthly_objects = ROMonthlyManager()

RO_log/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

RO_log/views.py
from urllib import response
from django.shortcuts import render
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.dates import TodayArchiveView
from django.db.models import Sum,Q
import datetime
from .models import RO,PayPeriod
from . import forms
from django.http import JsonResponse
from django.core.exceptions import ValidationError
from django.contrib import messages



# Create your views here

class CustomLoginView(LoginView):
    template_name = 'RO_log/login.html'
    fields = "__all__"
    # redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('RO_log:archive_day')

class SignUp(CreateView):
    template_name = 'RO_log/signup.html'
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('RO_log:archive_day')



class ROList(ListView):
    model = RO
    template_name = 'RO_log/RO_list.html'
    # paginate_by = 10

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = RO.objects.filter(user=self.request.user).filter(
        Q(RO_number__icontains=query)|Q(pay_period__name__icontains=query))
        return object_list



class ROCreate(LoginRequiredMixin,CreateView):
    model = RO
    fields = ['RO_number','hours_sold','work_performed','completed_date']

    def form_valid(self,form):
        form.instance.user = self.request.user
        form_date = form.instance.completed_date
        form.instance.pay_period = PayPeriod.objects.filter(start_date__lte=form_date,end_date__gte=form_date).get()
        
        return super().form_valid(form)
    



class ROUpdate(LoginRequiredMixin,UpdateView):
    model = RO
    fields = ['RO_number','user','hours_sold','work_performed','completed_date']

    def form_valid(self,form):
        form.instance.user = self.request.user
        form_date = form.instance.completed_date
        form.instance.pay_period = PayPeriod.objects.filter(start_date__lte=form_date,end_date__gte=form_date).get()
        return super().form_valid(form)


class RODelete(LoginRequiredMixin,DeleteView):
    model = RO
    success_url = reverse_lazy('RO_log:archive_day')

class ROTodayArchiveView(LoginRequiredMixin,TodayArchiveView):
    queryset = RO.objects.all()
    date_field = "completed_date"
    allow_empty = True
    context_object_name = 'daily_ros'

    def get_context_data(self, **kwargs):
        context=super(ROTodayArchiveView,self).get_context_data(**kwargs)
        context['daily_ros']=context['daily_ros'].filter(user=self.request.user)
        context['daily_total']=context['daily_ros'].filter(user=self.request.user).aggregate(Sum('hours_sold'))['hours_sold__sum']
        context['monthly_hours']=RO.monthly_objects.filter(user=self.request.user).aggregate(Sum('hours_sold'))['hours_sold__sum']
        return context

class PayPeriodList(LoginRequiredMixin,ListView):
    Model = PayPeriod
    queryset=PayPeriod.objects.all()
    context_object_name = 'payperiods'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['payperiods']=context['payperiods'].filter(user=self.request.user)
        return context

class PayPeriodCreate(LoginRequiredMixin,CreateView):
    model = PayPeriod
    fields = ['name','start_date','end_date']

    def form_valid(self,form):
        form.instance.user = self.request.user
        
        return super().form_valid(form)

class PayPeriodUpdate(LoginRequiredMixin,UpdateView):
    model = PayPeriod
    fields = ['name','start_date','end_date']

class PayPeriodDelete(LoginRequiredMixin,DeleteView):
    model = PayPeriod
    success_url = reverse_lazy('RO_log:PayPeriod_list')



class DashboardView(LoginRequiredMixin,ListView):
    template_name = 'RO_log/dashboard.html'
    queryset = PayPeriod.objects.all()
    context_object_name = 'payperiods'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['payperiodhours']=context['payperiods'].filter(user=self.request.user).annotate(Sum('ro__hours_sold'))
        return context


# RO.objects.values('pay_period__name').order_by('pay_period__name').annotate(
# Sum('hours_sold')
#

RO_log/templates/RO_log/Base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RO Tracker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<!-- bootstrap icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
<!-- custom CSS -->
<link rel="stylesheet" href="{% static 'RO_log/main.css' %}">
  </head>
<body>
  {% block navblock %}
<div class="navigation">
    <nav class="navbar navbar-expand-lg navbar-dark fs-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">RO tracker</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
             aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" href="{% url 'RO_log:archive_day' %}">Daily Log</a>
            <a class="nav-link active" href="{% url 'RO_log:payperiod-list' %}">Pay Periods</a>
            <a class="nav-link active" href="{% url 'RO_log:dashboard' %}">Dashboard</a>
            <a class="nav-link active" href="{% url 'RO_log:logout' %}">logout</a>
            <span class="navbar-text">
              <small>Logged in as {{request.user.username}}</small>
            </span>
            <form class="d-flex ms-3 h-50" action="{% url 'RO_log:report' %}" method="get">
              <input id='nav-search' class="form-control me-2" type="search" name="q"placeholder="Search" aria-label="Search">
            </form>
          </div>
        </div>
      </div>
    </nav>
</div>
{% endblock %}

{% block content %}

{% endblock %}

  </body>
</html>

RO_log/templates/RO_log/RO_archive_day.html
<!DOCTYPE html>

{% extends 'RO_log/Base.html'%}
{% block content %}


<div class="container">
  <div class="row mt-4">
    <div class="col-sm-6">
      <div class="card  text-center">
        <div class="card-header">
          Hours for today
        </div>
        <div class="card-body">
          <h5>{{ daily_total|floatformat|default:0 }}</h5>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card text-center">
          <div class="card-header">
          Hours for this month
          </div>
          <div class="card-body">
            <h5>{{ monthly_hours|floatformat|default:0 }}</h5>
          </div>
      </div>
    </div>
  </div>
</div>


  <!-- table -->
  <div class="d-grid gap-2 col-6 mx-auto my-5">
    <a class="btn rounded-pill" href="{% url 'RO_log:create' %}">Add New RO</a>
  </div>
<div class="container">
<table class="table table-sm table-borderless">
  <thead>
    <tr>
      <th scope="col">RO number</th>
      <th scope="col">Hours Sold</th>
      <th scope="col">Work Performed</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for ro in daily_ros %}
    <tr>
      <th>{{ro.RO_number}}</th>
      <td>{{ro.hours_sold}}</td>
      <td>{{ro.work_performed}}</td>
      <td>
        <a href="{% url 'RO_log:update' pk=ro.pk %}">
          <i class="bi-pencil-fill"></i>
        </a>
        <a href="{% url 'RO_log:delete' pk=ro.pk %}">
          <i class="bi-trash-fill" style = color:red;></i>
        </a>
      </td>
    </tr>
      {% empty %}
    <tr>
      <td>No Ro's today</td>
    </tr>

    {% endfor %}
</div>



{% endblock%}

RO_log/templates/RO_log/RO_confirm_delete.html
<!DOCTYPE html>

{% extends 'RO_log/Base.html'%}
{% block content %}

<div class="delete-card">
    <div class="card w-50 text-center ">
       <h5 class="card-header">Delete RO {{ro.RO_number}}?</h5>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="d-grid gap-2 mt-3">
              <input type="submit" class="btn rounded-pill" value="Delete">
            </div>
            <div class="d-grid gap-2 mt-3">
              <a class="btn rounded-pill" href="{% url 'RO_log:archive_day' %}">Cancel</a>
            </div>
          </form>
        </div>
    </div>
</div>

{% endblock%}

RO_log/templates/RO_log/RO_form.html
<!DOCTYPE html>

{% extends 'RO_log/Base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="Roform">
  <div class="d-flex justify-content-center">
      <div class="col-4">
        <form method="POST" class="post-form">
          <h1>RO form</h1>
          {% csrf_token %}
          {{form|crispy}}
          {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
             {{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close">
             <span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}
          <div class="d-grid gap-2 mt-3">
            <button type="submit" class="btn rounded-pill">Submit</button>
          </div>
        </form>
      </div>
  </div>
</div>




{% endblock %}

RO_log/templates/RO_log/RO_list.html
<!DOCTYPE html>

{% extends 'RO_log/Base.html'%}

{% block content %}


<div class="container mx-auto my-5">
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">RO number</th>
        <th scope="col">Hours Sold</th>
        <th scope="col">Work Performed</th>
        <th scope="col">Completed Date</th>
        <th scope="col">Pay Period</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>

      {% for ro in object_list %}
      <tr>
        <th>{{ro.RO_number}}</th>
        <td>{{ro.hours_sold}}</td>
        <td>{{ro.work_performed}}</td>
        <td>{{ro.completed_date}}</td>
        <td>{{ro.pay_period}}</td>
        <td>
          <a href="{% url 'RO_log:update' pk=ro.pk %}">
            <i class="bi-pencil-fill"></i>
          </a>
          <a href="{% url 'RO_log:delete' pk=ro.pk %}">
            <i class="bi-trash-fill"style = color:red;></i>
          </a>
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>


{% endblock %}

RO_log/templates/RO_log/dashboard.html
<!DOCTYPE html>


{% extends 'RO_log/Base.html'%}

{% block content %}
<div class="container mx-auto my-5">
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Pay Period </th>
        <th scope="col">Sold Hours</th>
      </tr>
    </thead>
    <tbody>

      {% for payperiodhour in payperiodhours %}
      <tr>
        <th>{{payperiodhour.name}}</th>
        <td>{{payperiodhour.ro__hours_sold__sum|floatformat}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock%}

RO_log/templates/RO_log/login.html
<!DOCTYPE html>
{% extends 'RO_log/Base.html'%}
{% load crispy_forms_tags %}

{% block navblock %}
{% endblock %}

{% block content %}
  <body>
    <div class="Roform">
      <div class="d-flex justify-content-center">
          <div class="col-4">
            <form method="POST" class="post-form">
              <h1>Login</h1>
              {% csrf_token %}
              {{form|crispy}}
              <div class="d-grid gap-2 mt-3">
                <button type="submit" class="btn rounded-pill">Login</button>
              </div>
              <p><small>not a member? click <a href="{% url 'RO_log:signup' %}">here</a> to sign up!</small></p>
            </form>
          </div>
      </div>
    </div>
  </body>
</html>

{% endblock %}

RO_log/templates/RO_log/payperiod_confirm_delete.html
<!DOCTYPE html>

{% extends 'RO_log/Base.html'%}
{% block content %}

<div class="delete-card">
    <div class="card w-50 text-center ">
       <h5 class="card-header">Delete Pay Period {{payperiod.name}}?</h5>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="d-grid gap-2 mt-3">
              <input type="submit" class="btn rounded-pill" value="Delete">
            </div>
            <div class="d-grid gap-2 mt-3">
              <a class="btn rounded-pill" href="{% url 'RO_log:payperiod-list' %}">Cancel</a>
            </div>
          </form>
        </div>
    </div>
</div>

{% endblock%}

RO_log/templates/RO_log/payperiod_form.html
<!DOCTYPE html>

{% extends 'RO_log/Base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="Roform">
  <div class="d-flex justify-content-center">
      <div class="col-4">
        <form method="POST" class="post-form">
          <h1>Pay Period form</h1>
          {% csrf_token %}
          {{form|crispy}}
          <div class="d-grid gap-2 mt-3">
            <button type="submit" class="btn rounded-pill">Submit</button>
          </div>
        </form>
      </div>
  </div>
</div>




{% endblock %}

RO_log/templates/RO_log/payperiod_list.html
<!DOCTYPE html>

{% extends 'RO_log/Base.html'%}
{% block content %}

<div class="d-grid gap-2 col-6 mx-auto my-5">
  <a class="btn rounded-pill" href="{% url 'RO_log:payperiod-create' %}">Add New Pay Period</a>
</div>

<div class="container mx-auto my-5">
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">Pay Period</th>
        <th scope="col">Start Date</th>
        <th scope="col">End Date</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>

      {% for payperiod in payperiods %}
      <tr>
        <th>{{payperiod.name}}</th>
        <td>{{payperiod.start_date}}</td>
        <td>{{payperiod.end_date}}</td>
        <td>
          <a href="{% url 'RO_log:payperiod-update' pk=payperiod.pk %}">
            <i class="bi-pencil-fill"></i>
          </a>
          <a href="{% url 'RO_log:payperiod-delete' pk=payperiod.pk %}">
            <i class="bi-trash-fill"style = color:red;></i>
          </a>
        </td>
      </tr>
      {% endfor %}

    </tbody>
  </table>
</div>


  {% endblock %}

RO_log/templates/RO_log/signup.html
<!DOCTYPE html>
{% extends 'RO_log/Base.html'%}
{% load crispy_forms_tags %}

{% block navblock %}
{% endblock %}

{% block content %}

  <body>
    <div class="Roform">
      <div class="d-flex justify-content-center">
          <div class="col-4">
            <form method="POST" class="post-form">
              <h1>Sign-Up</h1>
              {% csrf_token %}
              {{form|crispy}}
              <div class="d-grid gap-2 mt-3">
                <button type="submit" class="btn rounded-pill">SignUp</button>
              </div>
              <p><small>Already a member? click <a href="{% url 'RO_log:login' %}">here</a> to log in!</small></p>
            </form>
          </div>
      </div>
    </div>
  </body>
</html>

{% endblock %}